### ISSUE TITLE
Can you add a license file to RunHidden?

### ISSUE THREAD

**Issue by bburgin** [meshko/RunHidden#1]
meshko:

What license do you want for RunHidden?
Can you add a license file to the source?

Thanks,
bburgin

**Comment by meshko** [comment]
Hmmm... good question.  I have kind of lost track of what's a reasonable license these days.  Any suggestions?  MIT? BSD?  Something to say that you can do anything you want with it except killing kittens?

**Comment by bburgin** [comment]
Either MIT or BSD is fine with me. Thanks.

**Comment by meshko** [comment]
added BSD license
